Profile page updated
RoelMK/SEP-frontend pull request #36
Opened 2021-06-08 20:20 UTC by gabrielazanova

2021-06-08 21:03 UTC, nbalasovs requested changes

2021-06-08 21:03 UTC, nbalasovs commented on diabetes-dashboard/src/views/UserProfile.vue
> +                    <br/><br/>
Don't use br tags, you can always set margin, padding in the style section

2021-06-08 21:03 UTC, nbalasovs commented on diabetes-dashboard/src/views/UserProfile.vue
> +                    <br/><br/>
This as well

2021-06-08 21:03 UTC, nbalasovs commented on diabetes-dashboard/src/views/profileComponents/ProfileInfo.vue
> +                    <v-text-area id="personalValue">80</v-text-area>
Use p tag instead of v-text-area and remove default margin by settings `margin-bottom: 0` in styles

2021-06-09 07:04 UTC, JfmGijsbers commented on diabetes-dashboard/src/views/profileComponents/ProfileInfo.vue
> +                    <v-text-area id="personalValue">80</v-text-area>
Or alternatively, if the element only needs its padding set, you can use built-in bootstrap classes: "mt-0" for margin-top-0, or "ma-0" for margin-all-0 (same with padding: pt-0 etc)

2021-06-14 07:09 UTC, gabrielazanova commented on diabetes-dashboard/src/components/Navbar.vue
> +                    <v-text-area id="role">User</v-text-area>
I see it the same, but I am not sure what I should use then, p?

2021-06-15 08:01 UTC, JfmGijsbers approved these changes

2021-06-15 08:04 UTC, nbalasovs approved these changes

2021-06-15 08:05 UTC, merged