Feature/graph features
RoelMK/SEP-frontend pull request #9
Opened 2021-05-13 21:08 UTC by Vasil-VIS

Filtering of data in the line chart based on the selected activity, line chart for carbs, doughnut chart to display amount/percentage of time glucose values were High/Normal/Low. Probably modifications will need to be made once we can query the real data from the backend. The doughnut chart only shows the distribution for all of the glucose data since I can't get glucose values from a specific time frame. However, when querying can be done, I think fixing this will not be a problem.

2021-05-14 09:36 UTC, nbalasovs requested changes
There are things that should be changed. Quality of the code should be improved.

2021-05-14 09:36 UTC, nbalasovs commented on diabetes-dashboard/src/components/LineChart.vue
> +  </v-container>
That is a big nono. Components chart components should be independent of each other. You incorporated the doughnut chart into a line chart. The doughnut chart should have a separate vue file and should not be mixed with a line chart.

2021-05-14 09:36 UTC, nbalasovs commented on diabetes-dashboard/src/components/LineChart.vue
> +    };
You should place chart options into the data object

2021-05-14 09:36 UTC, nbalasovs commented on diabetes-dashboard/src/components/LineChart.vue
> +        let lowRangeMax = this.getHealthSettings.lowRangeMax;
This looks scary. Is there a more elegant way of doing this? If not I guess keep it like this

2021-05-14 09:36 UTC, nbalasovs commented on diabetes-dashboard/src/views/Dashboard.vue
> +          chosenActivity: { activity: null, now: ''},
why activity is initialized to null and now is an empty string?

2021-05-14 09:54 UTC, Vasil-VIS commented on diabetes-dashboard/src/components/LineChart.vue
> +  </v-container>
Isn't the vue file a component in which there is a canvas element in which the line chart resides? Since the v-calendar is also displayed there. The reason why I put it there is because I think the client wants to see not only the line chart of the glucose, but also the doughnut one at the same time. Otherwise, I might have to create almost the same component with another calendar and the user would have to set the same specified time frame twice for each chart. Do you have suggestions how this can be done in another way?

2021-05-14 09:54 UTC, Vasil-VIS commented on diabetes-dashboard/src/components/LineChart.vue
> +    };
I will resolve this tonight.

2021-05-14 09:54 UTC, Vasil-VIS commented on diabetes-dashboard/src/components/LineChart.vue
> +        let lowRangeMax = this.getHealthSettings.lowRangeMax;
I think once we have the data from the backend this will no longer be needed. I just made it like this because I wanted the chart to have some sort of functionality. I expect that we can get the amount/percentage of time for each type of glucose for a specified time frame from the back-end right? So that we will not have to manually compute this, like now.

2021-05-14 09:54 UTC, Vasil-VIS commented on diabetes-dashboard/src/views/Dashboard.vue
> +          chosenActivity: { activity: null, now: ''},
I just forgot to remove the first one, I will fix this tonight.

2021-05-14 10:04 UTC, nbalasovs commented on diabetes-dashboard/src/components/LineChart.vue
> +  </v-container>
I would suggest adding a separate component for the doughnut chart and placing it inside `App.vue` since we are going to fetch API data from `App.vue` and then send it to all other components. You can check #11 to see how it is likely going to be implemented.

2021-05-16 16:05 UTC, JfmGijsbers commented on diabetes-dashboard/src/components/DoughnutChart.vue
> +      showDoughnut: true,
unused

2021-05-16 16:05 UTC, JfmGijsbers commented on diabetes-dashboard/src/components/LineChart.vue
> +                <span v-on:click="displayChartX(chart, datasets.slice(0,2)), $emit('displayDoughnut', true)">Show: Glucose and Iron</span>
No need for ":" imo

2021-05-17 14:46 UTC, nbalasovs approved these changes
Looks much better!

2021-05-17 18:04 UTC, JfmGijsbers approved these changes

2021-05-17 18:04 UTC, merged